#version 450
#extension GL_ARB_separate_shader_objects : enable

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D u_shaded_image;

layout(set = 0, binding = 1) buffer exposure
{
	float    u_exposure;
};

void main()
{
	u_exposure = u_exposure * 0.99 + 0.01 * max(length(texture(u_shaded_image, vec2(0.5, 0.5)).xyz), 0.5); // TODO: this is awefully framerate dependent
}
